### ISSUE TITLE
No log in button on android.

### ISSUE THREAD

**Issue by ghost** [elvismercado/meteor-raix-push-demo#3]
Hello,
I tried to launch your application (it works) on an android phone and use it, still, there was no login button on the phone, and no sliding menu or something like that to « log in ». I can see the button in my desktop browser.
Is that normal ?

Screenshot: http://imgur.com/zxBSs7T

Full log of ./deploy.sh -android: http://sprunge.us/gYTH

Thank you.

**Comment by tltim** [comment]
how did you fix it?

**Comment by ghost** [comment]
Well it was a problem of configuration in the setup I used. I do not
remember exactly but pushing the app to the meteor servers and not using it
in « local » helped.

2015-07-21 21:56 GMT+02:00 tltim notifications@github.com:
